Vagrant.configure("2") do |config|
  config.vm.box = "dulin/mikrotik"

  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"

  config.ssh.keys_only = false
  config.ssh.insert_key = false

  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.network "forwarded_port", guest: 8728, host: 8728
  config.vm.network "forwarded_port", guest: 8291, host: 8291

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end
end

## config.vm.box = "dulin/mikrotik" 
## IS EXTREMELY OLD! - v6.37.4 only support LEGACY authentication => Use Winbox v3.41 !

# =>  https://portal.cloud.hashicorp.com/vagrant/discover?query=mikrotik
